# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'PokeApp' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PokeApp
  pod 'MBProgressHUD', '~> 0.9'
  pod 'Alamofire'
  pod 'Unbox'
  pod 'SVProgressHUD'
end
